// <auto-generated />
using System;
using AgendamentoPro.Infrastructure.Database.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendamentoPro.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AgendamentoProDbContext))]
    [Migration("20260520235443_AddWebPushSubscription")]
    partial class AddWebPushSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.Agendamento", b =>
                {
                    b.Property<int>("AgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AgeAcessoToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AgeAtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AgeCanceladoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AgeCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AgeData")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgeGrupoComboId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AgeHoraFim")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AgeHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeMotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeObservacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("AgePagamentoStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AgePercentualEntrada")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("AgeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AgeValorEntrada")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AgeValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("R_CliId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_RecId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_SerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgeId");

                    b.HasIndex("AgeAcessoToken")
                        .IsUnique();

                    b.HasIndex("AgeGrupoComboId");

                    b.HasIndex("R_CliId");

                    b.HasIndex("R_SerId");

                    b.HasIndex("R_TenId", "AgeData");

                    b.HasIndex("R_RecId", "AgeData", "AgeHoraInicio")
                        .IsUnique();

                    b.ToTable("Agendamento", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.AgendamentoRecorrente", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_CliId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_RecursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_SerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RecAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecDataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecDiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecFrequencia")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("RecHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecQuantidadeOcorrencias")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecId");

                    b.HasIndex("R_TenId", "RecAtivo");

                    b.ToTable("AgendamentoRecorrente", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.Avaliacao", b =>
                {
                    b.Property<int>("AvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvaComentario")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AvaCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AvaNota")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvaPublica")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AvaRespondidoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AvaToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("R_AgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_CliId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvaId");

                    b.HasIndex("AvaToken")
                        .IsUnique();

                    b.HasIndex("R_AgeId")
                        .IsUnique();

                    b.HasIndex("R_CliId");

                    b.HasIndex("R_TenId", "AvaRespondidoEm");

                    b.ToTable("Avaliacao", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.FotoAgendamento", b =>
                {
                    b.Property<int>("FotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FotCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotNomeOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FotTamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FotTipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("R_AgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FotId");

                    b.HasIndex("R_AgeId");

                    b.HasIndex("R_TenId", "R_AgeId");

                    b.ToTable("FotoAgendamento", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.ListaEspera", b =>
                {
                    b.Property<int>("LesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LesClienteEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LesClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LesClienteTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LesCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LesDataDesejada")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LesNotificado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LesNotificadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("LesObservacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("R_SerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LesId");

                    b.HasIndex("R_SerId");

                    b.HasIndex("R_TenId", "LesDataDesejada", "LesNotificado");

                    b.ToTable("ListaEspera", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Clientes.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CliCpf")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CliCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CliNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CliObservacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CliTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CliWhatsApp")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CliId");

                    b.HasIndex("R_TenId", "CliEmail");

                    b.HasIndex("R_TenId", "CliTelefone");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Clientes.PontosFidelidade", b =>
                {
                    b.Property<int>("PtsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PtsAtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("PtsSaldo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_CliId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PtsId");

                    b.HasIndex("R_CliId");

                    b.HasIndex("R_TenId", "R_CliId")
                        .IsUnique();

                    b.ToTable("PontosFidelidade", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Common.LogAuditoria", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogAcao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogChave")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogCorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogQuandoUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogTabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogUsuarioEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogValoresAntes")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogValoresDepois")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("R_UsuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("LogTabela", "LogChave");

                    b.HasIndex("R_TenId", "LogQuandoUtc");

                    b.ToTable("LogAuditoria", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Horarios.BloqueioAgenda", b =>
                {
                    b.Property<int>("BloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BloCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BloDataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BloDataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloMotivo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("R_RecId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BloId");

                    b.HasIndex("R_TenId");

                    b.ToTable("BloqueioAgenda", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Horarios.HorarioFuncionamento", b =>
                {
                    b.Property<int>("HorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HorAberto")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HorAbertura")
                        .HasColumnType("TEXT");

                    b.Property<int>("HorDiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HorFechamento")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HorPausaFim")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HorPausaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HorId");

                    b.HasIndex("R_TenId", "HorDiaSemana")
                        .IsUnique();

                    b.ToTable("HorarioFuncionamento", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Notificacoes.Notificacao", b =>
                {
                    b.Property<int>("NotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotCanal")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotDestinatario")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotEnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotErro")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotMensagem")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotTipo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("R_AgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotId");

                    b.HasIndex("R_TenId");

                    b.ToTable("Notificacao", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Pagamentos.Pagamento", b =>
                {
                    b.Property<int>("PagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PagAprovadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PagCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PagExpiracao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagForma")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PagGateway")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PagGatewayId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PagLinkPagamento")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PagPayloadGateway")
                        .HasColumnType("TEXT");

                    b.Property<string>("PagQrCode")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PagStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PagValor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("R_AgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PagId");

                    b.HasIndex("PagGatewayId")
                        .IsUnique();

                    b.HasIndex("R_AgeId");

                    b.HasIndex("R_TenId");

                    b.ToTable("Pagamento", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Pagamentos.WebhookEvento", b =>
                {
                    b.Property<int>("WhEvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhEvEventoId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhEvGateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhEvPayload")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WhEvProcessadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WhEvRecebidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhEvTipo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WhEvId");

                    b.HasIndex("WhEvGateway", "WhEvEventoId")
                        .IsUnique();

                    b.ToTable("WebhookEvento", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Recursos.Recurso", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RecAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecDescricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecOrdem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecTipo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RecId");

                    b.HasIndex("R_TenId", "RecAtivo");

                    b.ToTable("Recurso", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<int>("RefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_UsuId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RefCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RefExpiracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefJwtId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RefRevogado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RefUtilizado")
                        .HasColumnType("INTEGER");

                    b.HasKey("RefId");

                    b.HasIndex("R_UsuId");

                    b.HasIndex("RefToken")
                        .IsUnique();

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.Combo", b =>
                {
                    b.Property<int>("ComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ComCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComDescricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComOrdem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ComPrecoPromocional")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComId");

                    b.HasIndex("R_TenId", "ComAtivo");

                    b.ToTable("Combo", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.ComboServico", b =>
                {
                    b.Property<int>("ComServId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_ComId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_SerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComServId");

                    b.HasIndex("R_SerId");

                    b.HasIndex("R_ComId", "R_SerId")
                        .IsUnique();

                    b.ToTable("ComboServico", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.Cupom", b =>
                {
                    b.Property<int>("CupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CupAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CupCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CupCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CupTipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CupUsosFeitos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CupUsosMaximos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CupValidoAte")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CupValidoDe")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CupValor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CupId");

                    b.HasIndex("R_TenId", "CupCodigo")
                        .IsUnique();

                    b.ToTable("Cupom", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.PacotePrePago", b =>
                {
                    b.Property<int>("PctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PctAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PctCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PctNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PctPreco")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PctQuantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PctValidadeDias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_SerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PctId");

                    b.HasIndex("R_SerId");

                    b.HasIndex("R_TenId", "PctAtivo");

                    b.ToTable("PacotePrePago", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.SaldoPacote", b =>
                {
                    b.Property<int>("SaldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_CliId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_PctId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaldCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaldExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaldGatewayPagamentoId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SaldPagoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaldQuantidadeRestante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaldStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaldId");

                    b.HasIndex("R_PctId");

                    b.HasIndex("SaldGatewayPagamentoId");

                    b.HasIndex("R_TenId", "R_CliId");

                    b.ToTable("SaldoPacote", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.Servico", b =>
                {
                    b.Property<int>("SerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SerAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerCategoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SerCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerDescricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SerDuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("SerOrdem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SerPreco")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("SerId");

                    b.HasIndex("R_TenId", "SerAtivo");

                    b.ToTable("Servico", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Tenants.ConfiguracaoTenant", b =>
                {
                    b.Property<int>("CfgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CfgAtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CfgChave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CfgGrupo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CfgSensivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CfgValor")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CfgId");

                    b.HasIndex("R_TenId", "CfgChave")
                        .IsUnique();

                    b.ToTable("ConfiguracaoTenant", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Tenants.Tenant", b =>
                {
                    b.Property<int>("TenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenAntecedenciaMaxDias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenAntecedenciaMinHoras")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TenAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenBannerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenBufferMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenCep")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCnpj")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCorAcento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCorPrimaria")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCorSecundaria")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TenCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDescricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenEndereco")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenEstado")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenFaviconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenFonte")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenLimiteCancelamentoHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TenPercentualEntrada")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSegmento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenWhatsApp")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("TenId");

                    b.HasIndex("TenSlug")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Usuarios.OtpChallenge", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtpCodigoHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OtpCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OtpExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtpTelefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("OtpTentativas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OtpUsado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OtpId");

                    b.HasIndex("R_TenId", "OtpTelefone", "OtpCriadoEm");

                    b.ToTable("OtpChallenge", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Usuarios.PasswordReset", b =>
                {
                    b.Property<int>("RpsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_UsuId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RpsCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RpsExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("RpsToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RpsUsado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RpsUsadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("RpsId");

                    b.HasIndex("R_UsuId");

                    b.HasIndex("RpsToken")
                        .IsUnique();

                    b.ToTable("PasswordReset", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Excluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsuAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsuBloqueadoAte")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UsuCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuPerfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuTentativasFalhas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsuTotpAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuTotpSecret")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsuUltimoLogin")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuId");

                    b.HasIndex("R_TenId");

                    b.HasIndex("UsuEmail")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Usuarios.WebPushSubscription", b =>
                {
                    b.Property<int>("PushId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PushAuth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PushCriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PushP256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PushUltimoEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("PushUserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("R_TenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R_UsuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PushId");

                    b.HasIndex("PushEndpoint")
                        .IsUnique();

                    b.HasIndex("R_UsuId");

                    b.HasIndex("R_TenId", "R_UsuId");

                    b.ToTable("WebPushSubscription", (string)null);
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.Agendamento", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("R_CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Recursos.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("R_RecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Servicos.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("R_SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Recurso");

                    b.Navigation("Servico");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.AgendamentoRecorrente", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.Avaliacao", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Agendamentos.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("R_AgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("R_CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Cliente");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.FotoAgendamento", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Agendamentos.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("R_AgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.ListaEspera", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Servicos.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("R_SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Clientes.Cliente", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Clientes.PontosFidelidade", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("R_CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Horarios.BloqueioAgenda", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Horarios.HorarioFuncionamento", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Notificacoes.Notificacao", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Pagamentos.Pagamento", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Agendamentos.Agendamento", "Agendamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("R_AgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Recursos.Recurso", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("R_UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.Combo", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.ComboServico", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Servicos.Combo", "Combo")
                        .WithMany("Servicos")
                        .HasForeignKey("R_ComId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Servicos.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("R_SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.Cupom", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.PacotePrePago", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Servicos.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("R_SerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.SaldoPacote", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Servicos.PacotePrePago", "Pacote")
                        .WithMany()
                        .HasForeignKey("R_PctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacote");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.Servico", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Tenants.ConfiguracaoTenant", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Usuarios.PasswordReset", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("R_UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Usuarios.Usuario", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Usuarios.WebPushSubscription", b =>
                {
                    b.HasOne("AgendamentoPro.Core.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("R_TenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendamentoPro.Core.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("R_UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Agendamentos.Agendamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("AgendamentoPro.Core.Entities.Servicos.Combo", b =>
                {
                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
